apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang-app
spec:
  destination:
    name: "in-cluster"
    namespace: "default"
  source:
    path: golang-chart
    repoURL: "https://github.com/afr-dt/argocd-go"
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  project: "default"
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
